name: Build ISO

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Prepare pacman keyring
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
      
      - name: Install ArchISO
        run: |
          pacman -Sy
          pacman --noconfirm -S git archiso
      - name: Build ISO File
        run: |
          export OS_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          cp mkarchiso-doe /usr/bin
          chmod +x /usr/bin/mkarchiso-doe
          mkarchiso-doe -v .
          find out/
      - name: Upload ISO
        run: |
          echo "Uploading ISO..."
          ls out
          sleep 4
          curl --upload-file $(find out | grep .iso) https://transfer.sh/$(ls out | grep .iso)
